color: pink
fieldLayouts:
  d5aea1d3-eaf4-4039-b1ab-d44b3d3c0b53:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 8714394b-b8f8-45be-8d5f-4cb9d4fa9018
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            heading: 'Hero '
            type: craft\fieldlayoutelements\Heading
            uid: 13c3d1b1-41f0-4dbb-b1b0-5f796ef8f49b
            userCondition: null
          -
            elementCondition: null
            fieldUid: c37718a4-2455-456a-a28a-4ab755d1ddb3 # Titel
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a0eaa605-7549-4b6f-85a5-6387131a3c52
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: c37718a4-2455-456a-a28a-4ab755d1ddb3 # Titel
            handle: subTitle
            includeInCards: false
            instructions: null
            label: Ondertitel
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4e11705e-3e24-48cc-a796-30b6730d034a
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 9835d417-75ec-4190-a8a2-fb5eeabb0ec4 # Hero Afbeelding
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c588d941-2b45-40c1-917e-8160ff829285
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: 51686f2b-6bc3-4a0b-8dbd-7c3a6a445a0c
            userCondition: null
          -
            elementCondition: null
            fieldUid: fdc0c5de-9ce5-4a92-ad55-c589f3d4a8d6 # Sneakers
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d51ac987-38e2-4d55-85e6-f575b5af4fb5
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 3d056b00-f42d-47e4-bc30-e14f28ac55da # blokken
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 19bd82cb-9c2e-41eb-838f-087a2d144ff3
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 39f09732-54ea-46ae-b7e9-74ae28b004fe
        userCondition: null
handle: home
hasTitleField: false
icon: house
name: Startpagina
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: '{{"Startpagina"}}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
