color: null
fieldLayouts:
  c356ccf0-cd66-4b82-84dc-6501f751879c:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 1632b3d3-75ba-42d0-bd7a-c8514ace73ba
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: fd445757-8cfd-45f7-9b1a-65a583956b73 # Prijs
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3c156b75-7eae-46c3-a9a3-092f4782f697
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 770ce4a3-7ca8-4558-b014-479fcb4ddb5e # Afbeelding
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 64baa63c-9dad-4b86-b384-fc9e3e53fab6
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: b1818203-9eff-4584-9ea3-c39aab4fb3f0 # Kleur
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cd4d4642-d8f2-4d23-b38f-c23df3512f01
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 519de1f8-b162-4b04-8923-fb072747ba56 # Text
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 158e547b-6539-4723-be1a-e52c94bc680e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 3d056b00-f42d-47e4-bc30-e14f28ac55da # blokken
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 318bda92-6b2c-4675-9096-2bbb51334787
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: bde21532-8ac5-44fa-812a-e10b75cb5416
        userCondition: null
handle: sneakers
hasTitleField: true
icon: ''
name: Sneakers
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: ''
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: ''
titleTranslationMethod: site
