color: null
fieldLayouts:
  594463ef-a986-46ed-870b-22251a062491:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 0823564a-bfcd-40d7-88b7-f21902e8f333
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 5ddc1267-afd2-4195-8064-3477371ac127
        userCondition: null
handle: SneakersOverview
hasTitleField: true
icon: ''
name: 'Sneakers Overzicht'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
