columnSuffix: null
handle: sneakers
instructions: null
name: Sneakers
searchable: false
settings:
  allowSelfRelations: false
  branchLimit: null
  localizeRelations: false
  maintainHierarchy: false
  maxRelations: null
  minRelations: null
  selectionLabel: 'Selecteer een sneaker'
  showCardsInGrid: false
  showSiteMenu: false
  sources:
    - 'section:dea38989-2ed2-4db7-bc89-0bd073d6c182' # Sneakers
  targetSiteId: null
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: site
type: craft\fields\Entries
