defaultPlacement: end
enableVersioning: true
entryTypes:
  - a3e889f2-5ec0-4d28-879e-e83f828dab2f # Login
handle: login
maxAuthors: 1
name: Login
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  49adc719-ffd2-491a-832b-7c6defaf41fa: # Web Expert Engels
    enabledByDefault: true
    hasUrls: true
    template: _login.twig
    uriFormat: login
  df0d1799-8c87-4030-a2c5-1edfea893380: # Web Expert
    enabledByDefault: true
    hasUrls: true
    template: _login.twig
    uriFormat: login
type: single
